import type { Proyectos } from "@/interfaces/experience.interface";

export interface Proyectos_API extends Proyectos {
  category: 'frontend' | 'backend' | 'no_category';
  prioridad: "!!1" | "!!2" | "!!3" | "!!4";
}

export const proyectos: Proyectos_API[] = [
  {
    id: 1,
    name: "mario bros",
    title_es: "Clon Super Mario Bros",
    title_en: "Clon Super Mario Bros",
    body: {
      short_en:
        "This is a clone of the famous game Super Mario Bros, made with only TypeScript",
      long_en: "This is a clone of the famous game Super Mario Bros, made with only TypeScript, where you can play with the keyboard, and it is very entertaining, and can be played on any device.",
      short_es:
        "Este es un clon del famoso juego Super Mario Bros, hecho con solo TypeScript",
      long_es: "Este es un clon del famoso juego Super Mario Bros, hecho con solo TypeScript, donde puedes jugar con el teclado, y es muy entretenido, y se puede jugar en cualquier dispositivo.",
    },
    href: "https://visionary-mermaid-bdab86.netlify.app/",
    imageHref: "/img/marioBrosTs.webp",
    github: "https://github.com/angelcgar/mario-bros-ts",
    tags: ["/svg/ViteJs.svg", "/svg/TypeScript.svg", "/svg/HTML.svg"],
    category: "no_category",
    prioridad: "!!4",
  },
  {
    id: 2,
    name: "Lista de Tareas",
    title_es: "Lista de tareas",
    title_en: "Task List",
    body: {
      short_en: "This is my Task List, created using React and HTML.",
      long_en: "A to-do list developed with React that allows you to add, edit, and delete tasks easily and intuitively. Designed with a user-friendly interface to improve time management and productivity.",
      short_es: "Este es mi Lista de Tareas que fue hecho con React, en donde se puede agregar, eliminar y editar tareas..",
      long_es: "Lista de tareas desarrollada con React, que permite agregar, editar y eliminar tareas de manera sencilla e intuitiva. Diseñada con una interfaz amigable para mejorar la gestión del tiempo y la productividad.",
    },
    href: "https://spiffy-cascaron-6bc6ed.netlify.app/",
    imageHref: "/img/listaTareas.webp",
    github: "https://github.com/angelcgar/TSTodoList",
    tags: ["/svg/ViteJs.svg", "/svg/TypeScript.svg", "/svg/HTML.svg"],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 3,
    name: "Documentación",
    title_es: "Documentación",
    title_en: "Documentation",
    body: {
      short_en:
        "This is a Java documentation project where you can explore Java's documentation.",
      long_en: "Java documentation project that allows you to easily browse and reference the language documentation. Designed to provide easy access to key information about Java classes, methods, and features.",
      short_es:
        "Un proyecto de documentación de Java, en donde se puede ver la documentación de Java.",
      long_es: "Proyecto de documentación de Java que permite explorar y consultar fácilmente la documentación del lenguaje. Diseñado para facilitar el acceso a información clave sobre clases, métodos y características de Java.",
    },
    href: "https://documentacion-java.vercel.app/",
    imageHref: "/img/documentacion.webp",
    github: "https://github.com/angelcgar/documentacion-java",
    tags: ["/svg/Astro.svg", "/img/Starlight.webp", "/svg/HTML.svg"],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 4,
    name: "Candy crush",
    title_es: "Candy Crush",
    title_en: "Candy Crush",
    body: {
      short_en:
        "This is a clone of the famous Candy Crush game, built entirely with JavaScript.",
      long_en: "A clone of the classic Candy Crush game, developed solely with JavaScript. It allows keyboard play and is compatible with any device, offering an entertaining and accessible experience.",
      short_es:
        "Un clon del famoso juego Candy Crush, hecho con solo JavaScript.",
      long_es: "Clon del clásico juego Candy Crush, desarrollado únicamente con JavaScript. Permite jugar con el teclado y es compatible con cualquier dispositivo, ofreciendo una experiencia entretenida y accesible.",
    },
    href: "https://candy-crush-es.vercel.app/",
    imageHref: "/img/candyCrush.webp",
    github: "https://github.com/angelcgar/candy-crush-es",
    tags: ["/svg/ViteJs.svg", "/svg/JavaScript.svg", "/svg/CSS.svg"],
    category: "frontend",
    prioridad: "!!3",
  },
  {
    id: 5,
    name: "Juego de Snake",
    title_es: "Juego de Snake",
    title_en: "Snake Game",
    body: {
      short_en: "This is my Snake game, one of my first projects in NextJs.",
      long_en: "A Snake game developed with HTML, CSS, and JavaScript, one of my first projects. It allows keyboard play, offering a classic and dynamic experience.",
      short_es: "Juego de Snake desarrollado con HTML, CSS y JavaScript.",
      long_es: "Juego de Snake desarrollado con HTML, CSS y JavaScript, uno de mis primeros proyectos. Permite jugar usando el teclado, ofreciendo una experiencia clásica y dinámica.",
    },
    href: "https://65946ac2adc6ff0a49bef6c8--cheerful-tulumba-6526bc.netlify.app/",
    imageHref: "/img/snake.webp",
    github: "https://github.com/angelcgar/snake",
    tags: ["/svg/NextJs.svg", "/svg/React.svg", "/svg/CSS.svg"],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 6,
    name: "Buscador de peliculas",
    title_es: "Movie Searcher",
    title_en: "Movie Searcher",
    body: {
      short_en: "This is a movie searcher, built with React and HTML.",
      long_en: "Este es un buscador de peliculas, hecho con React, en donde se puede buscar peliculas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      short_es: "Este es un buscador de peliculas, hecho con React, en donde se puede buscar peliculas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      long_es: "Este es un buscador de peliculas, hecho con React, en donde se puede buscar peliculas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
    },
    href: "https://joyful-cannoli-81bf1e.netlify.app/",
    imageHref: "/img/peliculas.webp",
    github:
      "https://github.com/angelcgar/aprendiendo-react/tree/main/projects/05-react-buscador-peliculas",
    tags: [
      "/svg/ViteJs.svg",
      "/svg/React.svg",
      "/svg/HTML.svg",
      "/svg/CSS.svg",
    ],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 7,
    name: "Lista de Tareas",
    title_es: "My Task List",
    title_en: "My Task List",
    body: {
      short_en: "This is my Task List, created with React and LocalStorage.",
      long_en: "Este es mi Lista de Tareas que fue hecho con React y LocalStorage, en donde se puede agregar, eliminar y editar tareas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      short_es: "Este es mi Lista de Tareas que fue hecho con React y LocalStorage, en donde se puede agregar, eliminar y editar tareas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      long_es: "Este es mi Lista de Tareas que fue hecho con React y LocalStorage, en donde se puede agregar, eliminar y editar tareas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
    },
    href: "https://faztweb.github.io/react-tasksapp-localstorage/",
    imageHref: "/img/listaDeTareas.webp",
    github: "https://faztweb.github.io/react-tasksapp-localstorage/",
    tags: ["/svg/ViteJs.svg", "/svg/React.svg", "/svg/HTML.svg"],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 8,
    name: "Pokedex",
    title_es: "My Pokedex",
    title_en: "My Pokedex",
    body: {
      short_en: "This is my Pokedex, one of my first projects in React.",
      long_en: "Este es mi Pokedex, uno de mis primeros proyectos en React, en donde se puede buscar pokemones, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      short_es: "Este es mi Pokedex, uno de mis primeros proyectos en React, en donde se puede buscar pokemones, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      long_es: "Este es mi Pokedex, uno de mis primeros proyectos en React, en donde se puede buscar pokemones, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
    },
    href: "https://flourishing-kataifi-ea0631.netlify.app/",
    imageHref: "/img/pokedex.webp",
    github: "https://github.com/angelcgar/pokedex",
    tags: ["/svg/CSS.svg", "/svg/React.svg", "/svg/HTML.svg"],
    category: "frontend",
    prioridad: "!!1",
  },
  {
    id: 9,
    name: "calculadora",
    title_es: "My Calculator",
    title_en: "My Calculator",
    body: {
      short_en: "This is my Calculator, one of my first projects in React.",
      long_en: "Este es mi Calculadora, uno de mis primeros proyectos en React, en donde se puede hacer operaciones matematicas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      short_es: "Este es mi Calculadora, uno de mis primeros proyectos en React, en donde se puede hacer operaciones matematicas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
      long_es: "Este es mi Calculadora, uno de mis primeros proyectos en React, en donde se puede hacer operaciones matematicas, además de que es muy entretenido, y se puede jugar en cualquier dispositivo.",
    },
    href: "https://amazing-queijadas-ba02d4.netlify.app/",
    imageHref: "/img/calculadora.webp",
    github: "https://github.com/angelcgar/calculadora-react",
    tags: ["/svg/ViteJs.svg", "/svg/React.svg", "/svg/JavaScript.svg"],
    category: "backend",
    prioridad: "!!1",
  },
];
